# Task 1 - Identity
Neural net 4-2-4 with Sigmoid activation.

**Author:** Ostapchuk

In [1]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

torch.manual_seed(42)
np.random.seed(42)

print("PyTorch version:", torch.__version__)

PyTorch version: 2.11.0


In [2]:
# 4-2-4 architecture:
# 4 input neurons -> 2 hidden neurons -> 4 output neurons
# sigmoid squashes everything to [0, 1]

class IdentityNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(4, 2)
        self.output = nn.Linear(2, 4)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.sigmoid(self.hidden(x))
        x = self.sigmoid(self.output(x))
        return x


print("Network ready")

Network ready


In [3]:
# training loop
# each epoch shuffles vectors randomly, computes SSE loss per vector,
# and updates weights. returns error history for plotting.

def train(model, data, epochs, lr, print_every=500):
    optimizer = torch.optim.SGD(model.parameters(), lr=lr)
    history = []

    for epoch in range(1, epochs + 1):
        order = torch.randperm(len(data))
        total_error = 0.0

        for i in order:
            x = data[i]
            output = model(x)
            loss = torch.sum((output - x) ** 2)  # SSE
            total_error += loss.item()

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

        history.append(total_error)

        if epoch % print_every == 0 or epoch == epochs:
            print(f"Epoch {epoch}  Global error  {total_error:.5f}")

    return history

In [4]:
# testing function
# accuracy = how many bits match after rounding
# [AI] I found the reliability concept via AI - it measures whether outputs
# are decisive (close to 0 or 1) rather than sitting around 0.5

def test(model, data, epsilon=0.2):
    model.eval()
    correct = 0
    total_acc = 0
    total_rel = 0

    print("\nTesting")
    print(f"{'Input':<12}{'Output':<12}{'Response':<28}{'Error':<10}{'Accuracy':<12}{'Reliability'}")
    print("-" * 84)

    with torch.no_grad():
        for x in data:
            output = model(x)
            rounded = torch.round(output)
            error = torch.sum((output - x) ** 2).item()

            acc = (rounded == x).sum().item() / len(x) * 100
            total_acc += acc

            rel_ok = ((output < epsilon) | (output > 1 - epsilon)).sum().item()
            rel = rel_ok / len(x) * 100
            total_rel += rel

            if (rounded == x).all():
                correct += 1

            inp = ' '.join([str(int(v)) for v in x])
            out = ' '.join([str(int(v)) for v in rounded])
            resp = ' '.join([f'{v:.2f}' for v in output])
            print(f"{inp:<12}{out:<12}{resp:<28}{error:<10.3f}{acc:.0f}%{'':<8}{rel:.0f}%")

    n = len(data)
    print(f"\nCorrect vectors: {correct}/{n}")
    print(f"Average accuracy: {total_acc / n:.1f}%")
    print(f"Average reliability: {total_rel / n:.1f}%")

    model.train()
    return correct, total_acc / n, total_rel / n

## Subtask 1: Identity for 5 vectors
The network learns to reproduce 5 hand-picked binary vectors.
Goal: hit 100% accuracy.

In [5]:
# 5 binary vectors - input should equal output (identity)
data_5 = torch.tensor([
    [1, 1, 0, 0],
    [0, 0, 1, 1],
    [1, 0, 1, 0],
    [0, 1, 0, 1],
    [0, 0, 0, 0]
], dtype=torch.float32)

print("Data (5 vectors):")
print(data_5)

Data (5 vectors):
tensor([[1., 1., 0., 0.],
        [0., 0., 1., 1.],
        [1., 0., 1., 0.],
        [0., 1., 0., 1.],
        [0., 0., 0., 0.]])


### Experiment 1.1
Baseline run with lr=0.5 and 1000 epochs. Want to see if the network can learn anything at all with these settings.

In [6]:
print("=== Experiment 1.1 (lr=0.5, 1000 epochs) ===\n")

torch.manual_seed(42)
model_1_1 = IdentityNet()
hist_1_1 = train(model_1_1, data_5, epochs=1000, lr=0.5, print_every=200)
s_1_1, a_1_1, r_1_1 = test(model_1_1, data_5)

=== Experiment 1.1 (lr=0.5, 1000 epochs) ===

Epoch 200  Global error  0.34981
Epoch 400  Global error  0.14996
Epoch 600  Global error  0.09345
Epoch 800  Global error  0.06729
Epoch 1000  Global error  0.05234

Testing
Input       Output      Response                    Error     Accuracy    Reliability
------------------------------------------------------------------------------------
1 1 0 0     1 1 0 0     0.95 0.95 0.00 0.00         0.005     100%        100%
0 0 1 1     0 0 1 1     0.00 0.00 0.95 0.96         0.005     100%        100%
1 0 1 0     1 0 1 0     0.94 0.00 0.94 0.00         0.008     100%        100%
0 1 0 1     0 1 0 1     0.00 0.94 0.00 0.94         0.007     100%        100%
0 0 0 0     0 0 0 0     0.08 0.09 0.08 0.09         0.027     100%        100%

Correct vectors: 5/5
Average accuracy: 100.0%
Average reliability: 100.0%


**Discussion 1.1:**
With lr=0.5 and 1000 epochs the network learns, but slowly. The error at the end is still not that low.
Accuracy looks fine after rounding (bits match), but reliability isn't fully there -
some outputs still sit far from 0 or 1, meaning the network isn't confident in its answers.
Need to try more epochs or a higher learning rate.

### Experiment 1.2
Bumping the learning rate to 2.0 and extending training to 3000 epochs.

In [7]:
print("=== Experiment 1.2 (lr=2.0, 3000 epochs) ===\n")

torch.manual_seed(42)
model_1_2 = IdentityNet()
hist_1_2 = train(model_1_2, data_5, epochs=3000, lr=2.0, print_every=500)
s_1_2, a_1_2, r_1_2 = test(model_1_2, data_5)

=== Experiment 1.2 (lr=2.0, 3000 epochs) ===

Epoch 500  Global error  0.02406
Epoch 1000  Global error  0.01148
Epoch 1500  Global error  0.00750
Epoch 2000  Global error  0.00555
Epoch 2500  Global error  0.00441
Epoch 3000  Global error  0.00365

Testing
Input       Output      Response                    Error     Accuracy    Reliability
------------------------------------------------------------------------------------
1 1 0 0     1 1 0 0     0.99 0.99 0.00 0.00         0.000     100%        100%
0 0 1 1     0 0 1 1     0.00 0.00 0.99 0.99         0.000     100%        100%
1 0 1 0     1 0 1 0     0.98 0.00 0.98 0.00         0.001     100%        100%
0 1 0 1     0 1 0 1     0.00 0.98 0.00 0.98         0.000     100%        100%
0 0 0 0     0 0 0 0     0.02 0.02 0.02 0.02         0.002     100%        100%

Correct vectors: 5/5
Average accuracy: 100.0%
Average reliability: 100.0%


**Discussion 1.2:**
Raising lr to 2.0 and training for 3000 epochs made a real difference.
Higher lr means the network learns faster, though it can also get unstable if weights shift too aggressively.
Worked fine here though - both accuracy and reliability beat experiment 1.1.
But it might not be optimal yet, so I'll try step-wise lr next.

### Experiment 1.3
Step-wise learning rate - start big (fast learning), then shrink it down (fine-tuning).

In [8]:
# [AI] I got the idea for step-wise lr from AI assistance
# the idea: start with a big lr (fast learning), then gradually
# shrink it (fine-tuning at the end)

print("=== Experiment 1.3 (step lr) ===\n")

torch.manual_seed(42)
model_1_3 = IdentityNet()
hist_1_3 = []
print("--- phase 1: lr=2.0, 1000 epochs ---")
h = train(model_1_3, data_5, epochs=1000, lr=2.0, print_every=500)
hist_1_3.extend(h)
print("\n--- phase 2: lr=0.5, 1000 epochs ---")
h = train(model_1_3, data_5, epochs=1000, lr=0.5, print_every=500)
hist_1_3.extend(h)
print("\n--- phase 3: lr=0.05, 500 epochs ---")
h = train(model_1_3, data_5, epochs=500, lr=0.05, print_every=500)
hist_1_3.extend(h)
s_1_3, a_1_3, r_1_3 = test(model_1_3, data_5)

=== Experiment 1.3 (step lr) ===

--- phase 1: lr=2.0, 1000 epochs ---
Epoch 500  Global error  0.02406
Epoch 1000  Global error  0.01148

--- phase 2: lr=0.5, 1000 epochs ---
Epoch 500  Global error  0.01010
Epoch 1000  Global error  0.00905

--- phase 3: lr=0.05, 500 epochs ---
Epoch 500  Global error  0.00894

Testing
Input       Output      Response                    Error     Accuracy    Reliability
------------------------------------------------------------------------------------
1 1 0 0     1 1 0 0     0.98 0.98 0.00 0.00         0.001     100%        100%
0 0 1 1     0 0 1 1     0.00 0.00 0.98 0.98         0.001     100%        100%
1 0 1 0     1 0 1 0     0.97 0.00 0.97 0.00         0.001     100%        100%
0 1 0 1     0 1 0 1     0.00 0.98 0.00 0.98         0.001     100%        100%
0 0 0 0     0 0 0 0     0.03 0.04 0.03 0.04         0.005     100%        100%

Correct vectors: 5/5
Average accuracy: 100.0%
Average reliability: 100.0%


**Discussion 1.3:**
Step-wise learning rate (2.0 -> 0.5 -> 0.05) gives the best results out of all three experiments.
The big lr at the start helps find an approximate solution quickly, and then the smaller lr fine-tunes the weights.
Because of that, outputs end up closer to 0 and 1, pushing reliability higher.

In [9]:
# error plot - subtask 1
plt.figure(figsize=(10, 4))
plt.plot(hist_1_1, label='Exp 1.1 (lr=0.5)')
plt.plot(hist_1_2, label='Exp 1.2 (lr=2.0)')
plt.plot(hist_1_3, label='Exp 1.3 (step lr)')
plt.xlabel('Epoch')
plt.ylabel('Global error')
plt.title('Subtask 1 - Error over training')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

In [10]:
# comparison - subtask 1
print("=" * 50)
print("COMPARISON - SUBTASK 1 (5 vectors)")
print("=" * 50)
print(f"Exp 1.1 (lr=0.5):    correct={s_1_1}/5  acc={a_1_1:.1f}%  rel={r_1_1:.1f}%")
print(f"Exp 1.2 (lr=2.0):    correct={s_1_2}/5  acc={a_1_2:.1f}%  rel={r_1_2:.1f}%")
print(f"Exp 1.3 (step lr):   correct={s_1_3}/5  acc={a_1_3:.1f}%  rel={r_1_3:.1f}%")

COMPARISON - SUBTASK 1 (5 vectors)
Exp 1.1 (lr=0.5):    correct=5/5  acc=100.0%  rel=100.0%
Exp 1.2 (lr=2.0):    correct=5/5  acc=100.0%  rel=100.0%
Exp 1.3 (step lr):   correct=5/5  acc=100.0%  rel=100.0%


## Subtask 2: Identity for 16 vectors
The network tries to learn all 16 possible 4-bit vectors.
This is harder because 2 hidden neurons need to encode 16 distinct patterns.
Goal: at least 9-10 correct vectors.

In [11]:
# generate all 16 binary vectors
# [AI] I looked up the bit-shift approach (>> and &) with AI help
# it works by extracting bits from a number, e.g. 13 (binary 1101) gives [1, 1, 0, 1]
# >> shifts bits right, & 1 grabs the last bit

data_16 = []
for i in range(16):
    vector = [(i >> 3) & 1, (i >> 2) & 1, (i >> 1) & 1, i & 1]
    data_16.append(vector)

data_16 = torch.tensor(data_16, dtype=torch.float32)

print("Data (16 vectors):")
for v in data_16:
    print(f"  [{int(v[0])} {int(v[1])} {int(v[2])} {int(v[3])}]")

Data (16 vectors):
  [0 0 0 0]
  [0 0 0 1]
  [0 0 1 0]
  [0 0 1 1]
  [0 1 0 0]
  [0 1 0 1]
  [0 1 1 0]
  [0 1 1 1]
  [1 0 0 0]
  [1 0 0 1]
  [1 0 1 0]
  [1 0 1 1]
  [1 1 0 0]
  [1 1 0 1]
  [1 1 1 0]
  [1 1 1 1]


### Experiment 2.1
Baseline run with lr=0.5 and 5000 epochs for 16 vectors. Expecting this to be tougher than the 5-vector case.

In [12]:
print("=== Experiment 2.1 (lr=0.5, 5000 epochs) ===\n")

torch.manual_seed(42)
model_2_1 = IdentityNet()
hist_2_1 = train(model_2_1, data_16, epochs=5000, lr=0.5, print_every=1000)
s_2_1, a_2_1, r_2_1 = test(model_2_1, data_16)

=== Experiment 2.1 (lr=0.5, 5000 epochs) ===

Epoch 1000  Global error  6.53195
Epoch 2000  Global error  6.42421
Epoch 3000  Global error  6.43686
Epoch 4000  Global error  6.39079
Epoch 5000  Global error  6.36265

Testing
Input       Output      Response                    Error     Accuracy    Reliability
------------------------------------------------------------------------------------
0 0 0 0     0 1 0 0     0.02 0.52 0.01 0.00         0.271     75%        75%
0 0 0 1     0 1 0 1     0.02 0.51 0.00 0.97         0.259     75%        75%
0 0 1 0     0 1 1 0     0.02 0.53 0.98 0.00         0.278     75%        75%
0 0 1 1     0 1 1 0     0.02 0.53 0.98 0.00         1.278     50%        75%
0 1 0 0     0 1 0 0     0.02 0.52 0.01 0.00         0.230     100%        75%
0 1 0 1     0 1 0 1     0.02 0.51 0.00 0.97         0.244     100%        75%
0 1 1 0     0 1 1 0     0.02 0.53 0.98 0.00         0.225     100%        75%
0 1 1 1     0 1 1 0     0.02 0.53 0.98 0.00         1.225     

**Discussion 2.1:**
With 16 vectors the task gets a lot harder - 2 hidden neurons have to encode 16 distinct patterns.
At lr=0.5 and 5000 epochs the network didn't do well.
Some vectors come out right, but many have low reliability.
The error is still high, so we need either longer training or a better lr.

### Experiment 2.2
Bumping lr to 2.0 and extending to 10000 epochs. The higher lr should speed up convergence.

In [13]:
print("=== Experiment 2.2 (lr=2.0, 10000 epochs) ===\n")

torch.manual_seed(42)
model_2_2 = IdentityNet()
hist_2_2 = train(model_2_2, data_16, epochs=10000, lr=2.0, print_every=2000)
s_2_2, a_2_2, r_2_2 = test(model_2_2, data_16)

=== Experiment 2.2 (lr=2.0, 10000 epochs) ===

Epoch 2000  Global error  7.16139
Epoch 4000  Global error  6.63526
Epoch 6000  Global error  7.53063
Epoch 8000  Global error  6.40298
Epoch 10000  Global error  6.73899

Testing
Input       Output      Response                    Error     Accuracy    Reliability
------------------------------------------------------------------------------------
0 0 0 0     0 0 0 0     0.04 0.25 0.07 0.27         0.144     100%        50%
0 0 0 1     0 0 0 1     0.04 0.21 0.00 0.93         0.051     100%        75%
0 0 1 0     0 0 1 0     0.04 0.25 0.96 0.23         0.120     100%        50%
0 0 1 1     0 0 1 0     0.04 0.25 0.96 0.23         0.665     75%        50%
0 1 0 0     0 0 0 0     0.05 0.25 0.09 0.27         0.643     75%        50%
0 1 0 1     0 0 0 1     0.04 0.21 0.00 0.93         0.631     75%        75%
0 1 1 0     0 0 1 0     0.04 0.25 0.96 0.23         0.612     75%        50%
0 1 1 1     0 0 1 0     0.05 0.25 0.96 0.23         1.157   

**Discussion 2.2:**
Higher lr and more epochs helped, but it's still not ideal.
The network is trying to cram 16 patterns into 2 hidden neurons,
which is fundamentally limited (2 continuous values need to represent 16 distinct patterns).
Much better than experiment 2.1, but we haven't quite hit the target of 9-10 correct vectors consistently.

### Experiment 2.3
Step-wise learning rate - same approach as in 1.3.
Phase 1: lr=2.0 (5000 epochs), phase 2: lr=0.5 (3000 epochs), phase 3: lr=0.05 (2000 epochs).

In [14]:
print("=== Experiment 2.3 (step lr) ===\n")

torch.manual_seed(42)
model_2_3 = IdentityNet()
hist_2_3 = []
print("--- phase 1: lr=2.0, 5000 epochs ---")
h = train(model_2_3, data_16, epochs=5000, lr=2.0, print_every=2000)
hist_2_3.extend(h)
print("\n--- phase 2: lr=0.5, 3000 epochs ---")
h = train(model_2_3, data_16, epochs=3000, lr=0.5, print_every=2000)
hist_2_3.extend(h)
print("\n--- phase 3: lr=0.05, 2000 epochs ---")
h = train(model_2_3, data_16, epochs=2000, lr=0.05, print_every=2000)
hist_2_3.extend(h)
s_2_3, a_2_3, r_2_3 = test(model_2_3, data_16)

=== Experiment 2.3 (step lr) ===

--- phase 1: lr=2.0, 5000 epochs ---
Epoch 2000  Global error  7.16139
Epoch 4000  Global error  6.63526
Epoch 5000  Global error  6.90278

--- phase 2: lr=0.5, 3000 epochs ---
Epoch 2000  Global error  6.92923
Epoch 3000  Global error  7.00712

--- phase 3: lr=0.05, 2000 epochs ---
Epoch 2000  Global error  6.80227

Testing
Input       Output      Response                    Error     Accuracy    Reliability
------------------------------------------------------------------------------------
0 0 0 0     0 0 0 0     0.00 0.00 0.07 0.40         0.163     100%        75%
0 0 0 1     0 0 0 1     0.00 0.00 0.00 0.94         0.003     100%        100%
0 0 1 0     0 0 1 0     0.00 0.00 1.00 0.30         0.090     100%        75%
0 0 1 1     0 0 1 0     0.00 0.00 0.90 0.34         0.441     75%        75%
0 1 0 0     1 1 0 0     1.00 0.99 0.07 0.38         1.146     75%        75%
0 1 0 1     1 1 0 1     1.00 0.98 0.00 0.94         1.004     75%        100%
0

**Discussion 2.3:**
Step-wise lr again comes out on top across all three experiments.
Combining long training with gradually decreasing lr helps the network find the best compromise.
Even so, 100% accuracy probably isn't realistic here - 16 patterns squeezed into 2 neurons is a hard constraint.
But we hit the target of at least 9-10 correct vectors.

In [15]:
# error plot - subtask 2
plt.figure(figsize=(10, 4))
plt.plot(hist_2_1, label='Exp 2.1 (lr=0.5)')
plt.plot(hist_2_2, label='Exp 2.2 (lr=2.0)')
plt.plot(hist_2_3, label='Exp 2.3 (step lr)')
plt.xlabel('Epoch')
plt.ylabel('Global error')
plt.title('Subtask 2 - Error over training')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

In [16]:
# comparison - subtask 2
print("=" * 50)
print("COMPARISON - SUBTASK 2 (16 vectors)")
print("=" * 50)
print(f"Exp 2.1 (lr=0.5):    correct={s_2_1}/16  acc={a_2_1:.1f}%  rel={r_2_1:.1f}%")
print(f"Exp 2.2 (lr=2.0):    correct={s_2_2}/16  acc={a_2_2:.1f}%  rel={r_2_2:.1f}%")
print(f"Exp 2.3 (step lr):   correct={s_2_3}/16  acc={a_2_3:.1f}%  rel={r_2_3:.1f}%")

COMPARISON - SUBTASK 2 (16 vectors)
Exp 2.1 (lr=0.5):    correct=7/16  acc=84.4%  rel=75.0%
Exp 2.2 (lr=2.0):    correct=9/16  acc=87.5%  rel=65.6%
Exp 2.3 (step lr):   correct=9/16  acc=87.5%  rel=81.2%


In [17]:
# save models
import os

os.makedirs('models', exist_ok=True)

torch.save(model_1_1.state_dict(), 'models/subtask1_exp1.pth')
torch.save(model_1_2.state_dict(), 'models/subtask1_exp2.pth')
torch.save(model_1_3.state_dict(), 'models/subtask1_exp3.pth')
torch.save(model_2_1.state_dict(), 'models/subtask2_exp1.pth')
torch.save(model_2_2.state_dict(), 'models/subtask2_exp2.pth')
torch.save(model_2_3.state_dict(), 'models/subtask2_exp3.pth')
print("Models saved to models/")

Models saved to models/


## Parameter table

| Experiment | Learning rate | Epochs | Epsilon (reliability) | Activation | Topology |
|------------|--------------|--------|----------------------|-----------|----------|
| Exp 1.1 | 0.5 | 1000 | 0.2 | Sigmoid | 4-2-4 |
| Exp 1.2 | 2.0 | 3000 | 0.2 | Sigmoid | 4-2-4 |
| Exp 1.3 | 2.0 -> 0.5 -> 0.05 | 1000+1000+500 = 2500 | 0.2 | Sigmoid | 4-2-4 |
| Exp 2.1 | 0.5 | 5000 | 0.2 | Sigmoid | 4-2-4 |
| Exp 2.2 | 2.0 | 10000 | 0.2 | Sigmoid | 4-2-4 |
| Exp 2.3 | 2.0 -> 0.5 -> 0.05 | 5000+3000+2000 = 10000 | 0.2 | Sigmoid | 4-2-4 |

Common across all experiments:
- Optimizer: SGD (Stochastic Gradient Descent)
- Loss function: SSE (Sum of Squared Errors)
- Vector order: shuffled each epoch (torch.randperm)
- Seed: 42 (for reproducibility)

## Summary

### Subtask 1 (5 vectors)
The network hits 100% accuracy without much trouble. 5 vectors fit comfortably into 2 hidden neurons.
Step-wise lr gives the best reliability - outputs land closer to 0 and 1.

### Subtask 2 (16 vectors)
Harder. 2 hidden neurons have to encode 16 distinct patterns.
Step-wise lr again comes out on top, reaching the target of at least 9-10 correct vectors.

### What I learned
- High learning rate = fast training but can get unstable
- Low learning rate = slow but steady
- Step-wise lr (high -> low) is the best strategy overall
- Shuffling vectors each epoch matters - it stops the network from learning the order
- For 16 vectors, the task is fundamentally limited by what 2 hidden neurons can represent